import Head from 'next/head'

// import UberHeaderHOME from './_header'

export default function HomeIN() {
  return (
    <>
      <Head>
        <title>Ibz App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='version'>APP VERSION: V1.1.0WW</h1>
      <h1 className='createdon'></h1>
      <h1 className='archon'></h1>
       < a href="https://ibz.vercel.app/EN"><h1>CLICK HERE TO CONTINUE TO THE ENGLISH SIDE</h1></a>
       < a href="https://ibz.vercel.app/DE"><h1>KLICKEN SIE HIER, UM ZUR DEUTSCHEN SEITE ZU GEHEN</h1></a>
       <br /><br /><br />
<h3>Product of 2023</h3>
      <br /><br /><br /><br />
    {/* <UberHeaderHOME/> */}
    </>
  )
}
